### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by zaaack** [zlq4863947/dripjs#35]
TypeError: Cannot read property 'headers' of undefined
    at Bar.request (/c/Users/z/Projects/turtle/node_modules/dripjs/dist/modules/exchanges/crypto/bitmex/rest/internal/rest.js:57:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```diff
 try {
            const response = await axios_1.default(url, request);
            const ratelimit = common_1.getRateLimit(response.headers);
            this.remaining = ratelimit.remaining;
            return {
                ratelimit,
                body: response.data,
            };
        }
        catch (error) {
+          console.error(error)
            return {
                ratelimit: common_1.getRateLimit(errro.response.headers),
                body: {},
                error: error.response.data.error,
            };
        }

```

**Comment by zlq4863947** [comment]
Error handling is still in TODO, I'll do it later
